# Generated by Django 3.1.2 on 2020-10-14 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='especialista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tipo_doc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pacientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField()),
                ('peso', models.PositiveIntegerField()),
                ('estatura', models.PositiveIntegerField()),
                ('estado_civil', models.CharField(max_length=45)),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.tipo_doc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Numero_doc', models.PositiveIntegerField()),
                ('telefono', models.PositiveIntegerField()),
                ('especialista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.especialista')),
                ('tipo_doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.tipo_doc')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='historia_clinica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incapacidad', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo_consulta', models.TextField(max_length=150)),
                ('enfermedades_actual', models.CharField(max_length=150)),
                ('antecedentes', models.CharField(max_length=150)),
                ('analisis', models.CharField(max_length=150)),
                ('plan_manejo', models.CharField(max_length=150)),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='grupo_familiar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(max_length=50)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.medico')),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='citas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.medico')),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appconsultaeps.pacientes')),
            ],
        ),
    ]
