# Generated by Django 3.1.2 on 2020-10-14 21:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appconsultaeps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo_familiar',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='grupo_familiar',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='historia_clinica',
            name='pacientes',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialista',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='tipo_doc',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='user',
        ),
        migrations.AlterField(
            model_name='pacientes',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='citas',
        ),
        migrations.DeleteModel(
            name='especialista',
        ),
        migrations.DeleteModel(
            name='grupo_familiar',
        ),
        migrations.DeleteModel(
            name='historia_clinica',
        ),
        migrations.DeleteModel(
            name='medico',
        ),
    ]
